name: Teardown Preview

on:
  pull_request:
    types:
      - closed

concurrency:
  group: preview-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: false

jobs:
  teardown:
    name: Teardown Preview
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.head.ref != 'main' }}

    environment: Preview

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Clean branch name
        id: clean-branch-name
        uses: ./.github/actions/clean-branch-name
        with:
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Set stage
        run: |
          echo "STAGE=preview-${{ steps.clean-branch-name.outputs.clean_branch_name }}" >> $GITHUB_ENV

      - name: Load secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_API_TOKEN: op://corporation-preview/Cloudflare/api-token
          ALCHEMY_PASSWORD: op://corporation-preview/Alchemy/password

      - name: Destroy Alchemy resources
        run: bun run --filter @corporation/infra destroy
